fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=100"]
      - id: check-ast
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: debug-statements

  - repo: https://github.com/asottile/pyupgrade
    rev: v1.19.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.1
    hooks:
      - id: rst-backticks
      # - id: python-no-log-warn
      - id: python-no-eval
      - id: python-check-mock-methods
      - id: python-check-blanket-noqa

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
